clean:
	$(MAKE) -C server0 clean
	$(MAKE) -C server1 clean
	$(MAKE) -C server2 clean
	$(MAKE) -C server3 clean
	$(MAKE) -C server4 clean
	$(MAKE) -C client0 clean
	$(MAKE) -C client1 clean
	$(MAKE) -C client2 clean
	$(MAKE) -C client3 clean
	$(MAKE) -C client4 clean
	$(MAKE) -C client5 clean
	$(MAKE) -C client6 clean
	$(MAKE) -C client7 clean
	$(MAKE) -C client8 clean
	$(MAKE) -C client9 clean
