// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft.proto

It has these top-level messages:
	RequestVoteRequest
	RequestVoteResponse
	AppendEntriesRequest
	AppendEntriesResponse
	LogEntry
	PersistentState
	ExecuteCommandRequest
	ExecuteCommandResponse
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestVoteRequest struct {
	CandidateId  int64 `protobuf:"varint,1,opt,name=candidateId" json:"candidateId,omitempty"`
	Term         int64 `protobuf:"varint,2,opt,name=term" json:"term,omitempty"`
	LastLogIndex int64 `protobuf:"varint,3,opt,name=lastLogIndex" json:"lastLogIndex,omitempty"`
	LastLogTerm  int64 `protobuf:"varint,4,opt,name=lastLogTerm" json:"lastLogTerm,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestVoteRequest) GetCandidateId() int64 {
	if m != nil {
		return m.CandidateId
	}
	return 0
}

func (m *RequestVoteRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	Term        int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool  `protobuf:"varint,2,opt,name=voteGranted" json:"voteGranted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestVoteResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteResponse) GetVoteGranted() bool {
	if m != nil {
		return m.VoteGranted
	}
	return false
}

type AppendEntriesRequest struct {
	Term         int64       `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId     int64       `protobuf:"varint,2,opt,name=leaderId" json:"leaderId,omitempty"`
	PrevLogIndex int64       `protobuf:"varint,3,opt,name=prevLogIndex" json:"prevLogIndex,omitempty"`
	PrevLogTerm  int64       `protobuf:"varint,4,opt,name=prevLogTerm" json:"prevLogTerm,omitempty"`
	CommitIndex  int64       `protobuf:"varint,5,opt,name=commitIndex" json:"commitIndex,omitempty"`
	Entries      []*LogEntry `protobuf:"bytes,6,rep,name=entries" json:"entries,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesRequest) GetLeaderId() int64 {
	if m != nil {
		return m.LeaderId
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if m != nil {
		return m.PrevLogIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntriesRequest) GetCommitIndex() int64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesRequest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Term         int64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	NextLogIndex int64 `protobuf:"varint,2,opt,name=nextLogIndex" json:"nextLogIndex,omitempty"`
	Success      bool  `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AppendEntriesResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetNextLogIndex() int64 {
	if m != nil {
		return m.NextLogIndex
	}
	return 0
}

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LogEntry struct {
	Term    int64  `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Index   int64  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Command []byte `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogEntry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *LogEntry) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *LogEntry) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type PersistentState struct {
	CurrentTerm int64       `protobuf:"varint,1,opt,name=currentTerm" json:"currentTerm,omitempty"`
	VotedFor    int64       `protobuf:"varint,2,opt,name=votedFor" json:"votedFor,omitempty"`
	Log         []*LogEntry `protobuf:"bytes,3,rep,name=log" json:"log,omitempty"`
}

func (m *PersistentState) Reset()                    { *m = PersistentState{} }
func (m *PersistentState) String() string            { return proto.CompactTextString(m) }
func (*PersistentState) ProtoMessage()               {}
func (*PersistentState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PersistentState) GetCurrentTerm() int64 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *PersistentState) GetVotedFor() int64 {
	if m != nil {
		return m.VotedFor
	}
	return 0
}

func (m *PersistentState) GetLog() []*LogEntry {
	if m != nil {
		return m.Log
	}
	return nil
}

type ExecuteCommandRequest struct {
	Command []byte `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
}

func (m *ExecuteCommandRequest) Reset()                    { *m = ExecuteCommandRequest{} }
func (m *ExecuteCommandRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteCommandRequest) ProtoMessage()               {}
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExecuteCommandRequest) GetCommand() []byte {
	if m != nil {
		return m.Command
	}
	return nil
}

type ExecuteCommandResponse struct {
	Success       bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ServerAddress string `protobuf:"bytes,2,opt,name=serverAddress" json:"serverAddress,omitempty"`
	Answer        []byte `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (m *ExecuteCommandResponse) Reset()                    { *m = ExecuteCommandResponse{} }
func (m *ExecuteCommandResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteCommandResponse) ProtoMessage()               {}
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ExecuteCommandResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ExecuteCommandResponse) GetServerAddress() string {
	if m != nil {
		return m.ServerAddress
	}
	return ""
}

func (m *ExecuteCommandResponse) GetAnswer() []byte {
	if m != nil {
		return m.Answer
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*PersistentState)(nil), "raft.PersistentState")
	proto.RegisterType((*ExecuteCommandRequest)(nil), "raft.ExecuteCommandRequest")
	proto.RegisterType((*ExecuteCommandResponse)(nil), "raft.ExecuteCommandResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Raft service

type RaftClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
}

type raftClient struct {
	cc *grpc.ClientConn
}

func NewRaftClient(cc *grpc.ClientConn) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := grpc.Invoke(ctx, "/raft.Raft/ExecuteCommand", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Raft service

type RaftServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Raft_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.Raft/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _Raft_RequestVote_Handler,
		},
		{
			MethodName: "AppendEntries",
			Handler:    _Raft_AppendEntries_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _Raft_ExecuteCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xfe, 0xf3, 0xa7, 0xeb, 0xca, 0x69, 0x37, 0x24, 0xb3, 0x4d, 0x21, 0x70, 0x11, 0x59, 0x5c,
	0xf4, 0x6a, 0x12, 0xe3, 0x09, 0x26, 0x18, 0xa8, 0x30, 0x10, 0x0a, 0x13, 0xf7, 0xa6, 0x3e, 0xab,
	0x22, 0xb5, 0x76, 0x66, 0x9f, 0x96, 0xf2, 0x16, 0x3c, 0x1e, 0x6f, 0xc0, 0x6b, 0x20, 0x3b, 0x71,
	0xeb, 0x94, 0x88, 0x3b, 0x9f, 0xef, 0xc4, 0x9f, 0xbf, 0xef, 0x3b, 0x76, 0x00, 0x8c, 0xb8, 0xa7,
	0xcb, 0xda, 0x68, 0xd2, 0x6c, 0xe0, 0xd6, 0xfc, 0x67, 0x02, 0xac, 0xc4, 0x87, 0x35, 0x5a, 0xfa,
	0xaa, 0x09, 0xdb, 0x25, 0x2b, 0x60, 0x3c, 0x17, 0x4a, 0x56, 0x52, 0x10, 0xce, 0x64, 0x96, 0x14,
	0xc9, 0x34, 0x2d, 0x63, 0x88, 0x31, 0x18, 0x10, 0x9a, 0x55, 0xf6, 0xbf, 0x6f, 0xf9, 0x35, 0xe3,
	0x30, 0x59, 0x0a, 0x4b, 0xb7, 0x7a, 0x31, 0x53, 0x12, 0xb7, 0x59, 0xea, 0x7b, 0x1d, 0xcc, 0x31,
	0xb7, 0xf5, 0x9d, 0xdb, 0x3e, 0x68, 0x98, 0x23, 0x88, 0x7f, 0x80, 0x27, 0x1d, 0x45, 0xb6, 0xd6,
	0xca, 0xe2, 0xee, 0xc0, 0x24, 0x3a, 0xb0, 0x80, 0xf1, 0x46, 0x13, 0xbe, 0x33, 0x42, 0x11, 0x4a,
	0xaf, 0x65, 0x54, 0xc6, 0x10, 0xff, 0x95, 0xc0, 0xd9, 0x75, 0x5d, 0xa3, 0x92, 0x37, 0x8a, 0x4c,
	0x85, 0x36, 0x38, 0xec, 0xa3, 0xcb, 0x61, 0xb4, 0x44, 0x21, 0xd1, 0xcc, 0x64, 0xeb, 0x6b, 0x57,
	0x3b, 0x6f, 0xb5, 0xc1, 0xcd, 0xa1, 0xb7, 0x18, 0x73, 0x72, 0xda, 0x3a, 0xf6, 0x16, 0x41, 0x3e,
	0x57, 0xbd, 0x5a, 0x55, 0xd4, 0x90, 0x1c, 0xb5, 0xb9, 0xee, 0x21, 0x36, 0x85, 0x63, 0x6c, 0x94,
	0x66, 0xc3, 0x22, 0x9d, 0x8e, 0xaf, 0x4e, 0x2f, 0xfd, 0xd0, 0x6e, 0xf5, 0xc2, 0x39, 0xf8, 0x51,
	0x86, 0x36, 0xaf, 0xe0, 0xfc, 0xc0, 0xd9, 0x3f, 0x92, 0xe2, 0x30, 0x51, 0xb8, 0xdd, 0x8f, 0xa6,
	0xb1, 0xd7, 0xc1, 0x58, 0x06, 0xc7, 0x76, 0x3d, 0x9f, 0xa3, 0xb5, 0xde, 0xdd, 0xa8, 0x0c, 0x25,
	0xff, 0x04, 0xa3, 0x70, 0x7e, 0x2f, 0xfb, 0x19, 0x1c, 0x55, 0x11, 0x6d, 0x53, 0x38, 0x3e, 0xe7,
	0x4c, 0x28, 0xe9, 0xf9, 0x26, 0x65, 0x28, 0xf9, 0x03, 0x3c, 0xfe, 0x8c, 0xc6, 0x56, 0x96, 0x50,
	0xd1, 0x17, 0x12, 0x84, 0x3e, 0x99, 0xb5, 0x31, 0xa8, 0xe8, 0x6e, 0xcf, 0x1e, 0x43, 0x6e, 0x3a,
	0x6e, 0xb2, 0xf2, 0xad, 0x36, 0x61, 0x3a, 0xa1, 0x66, 0x05, 0xa4, 0x4b, 0xbd, 0xc8, 0xd2, 0xde,
	0xc4, 0x5c, 0x8b, 0xbf, 0x84, 0xf3, 0x9b, 0x2d, 0xce, 0xd7, 0x84, 0xaf, 0x1b, 0x11, 0xe1, 0x22,
	0x44, 0x2a, 0x93, 0xae, 0xca, 0x1a, 0x2e, 0x0e, 0xb7, 0xb4, 0x09, 0x47, 0x49, 0x25, 0x9d, 0xa4,
	0xd8, 0x0b, 0x38, 0xb1, 0x68, 0x36, 0x68, 0xae, 0xa5, 0x34, 0xae, 0xef, 0x94, 0x3e, 0x2a, 0xbb,
	0x20, 0xbb, 0x80, 0xa1, 0x50, 0xf6, 0x3b, 0x9a, 0x36, 0x98, 0xb6, 0xba, 0xfa, 0x9d, 0xc0, 0xa0,
	0x14, 0xf7, 0xc4, 0xde, 0xc0, 0x38, 0x7a, 0x03, 0x2c, 0x6b, 0x1c, 0xfd, 0xfd, 0x50, 0xf3, 0xa7,
	0x3d, 0x9d, 0x46, 0x24, 0xff, 0x8f, 0xbd, 0x87, 0x93, 0xce, 0x0d, 0x61, 0x79, 0xf3, 0x75, 0xdf,
	0x83, 0xc8, 0x9f, 0xf5, 0xf6, 0x76, 0x5c, 0x1f, 0xe1, 0xb4, 0x1b, 0x06, 0x6b, 0x37, 0xf4, 0xa6,
	0x9a, 0x3f, 0xef, 0x6f, 0x06, 0xba, 0x6f, 0x43, 0xff, 0x13, 0x7a, 0xf5, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x90, 0x00, 0xdd, 0x50, 0x92, 0x04, 0x00, 0x00,
}
